# Generated by Django 3.1.6 on 2021-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20210206_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(default='México', max_length=50),
        ),
    ]
