# Generated by Django 3.1.6 on 2021-02-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20210206_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='num_entidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='num_pais',
            field=models.IntegerField(default=0),
        ),
    ]
